// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbzv_FRDU8043uuM1hMykebr7cA4fLcLg',
    appId: '1:79175676104:web:0edcc4c1cdcc589e0335fd',
    messagingSenderId: '79175676104',
    projectId: 'stockflow-19fb4',
    authDomain: 'stockflow-19fb4.firebaseapp.com',
    databaseURL: 'https://stockflow-19fb4-default-rtdb.firebaseio.com',
    storageBucket: 'stockflow-19fb4.firebasestorage.app',
    measurementId: 'G-659TX32NQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKW9oRO1mCBEoZjIth5XZMybz0CxX7sCU',
    appId: '1:79175676104:android:d96ed135b264e9640335fd',
    messagingSenderId: '79175676104',
    projectId: 'stockflow-19fb4',
    databaseURL: 'https://stockflow-19fb4-default-rtdb.firebaseio.com',
    storageBucket: 'stockflow-19fb4.firebasestorage.app',
  );
}
